//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: CollectionUsageFinderProtocol.kt:9</p>
  /// </summary>
  [JetBrains.Application.ShellComponent(Application.Parts.Instantiation.DemandAnyThreadSafe)]
  public class CollectionUsageFinderProtocol : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public RdCall<CollectionUsageFindRequest, CollectionUsageFindResponse> FindCollectionUsages => _FindCollectionUsages;
    
    //private fields
    [NotNull] private readonly RdCall<CollectionUsageFindRequest, CollectionUsageFindResponse> _FindCollectionUsages;
    
    //primary constructor
    private CollectionUsageFinderProtocol(
      [NotNull] RdCall<CollectionUsageFindRequest, CollectionUsageFindResponse> findCollectionUsages
    )
    {
      if (findCollectionUsages == null) throw new ArgumentNullException("findCollectionUsages");
      
      _FindCollectionUsages = findCollectionUsages;
      BindableChildren.Add(new KeyValuePair<string, object>("findCollectionUsages", _FindCollectionUsages));
    }
    //secondary constructor
    private CollectionUsageFinderProtocol (
    ) : this (
      new RdCall<CollectionUsageFindRequest, CollectionUsageFindResponse>(CollectionUsageFindRequest.Read, CollectionUsageFindRequest.Write, CollectionUsageFindResponse.Read, CollectionUsageFindResponse.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -6506649137475799515L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    public CollectionUsageFinderProtocol(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("CollectionUsageFinderProtocol"));
      this.BindTopLevel(lifetime, protocol, "CollectionUsageFinderProtocol");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("CollectionUsageFinderProtocol (");
      using (printer.IndentCookie()) {
        printer.Print("findCollectionUsages = "); _FindCollectionUsages.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: CollectionUsageFinderProtocol.kt:10</p>
  /// </summary>
  public sealed class CollectionUsageFindRequest : IPrintable, IEquatable<CollectionUsageFindRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    public int CaretOffset {get; private set;}
    
    //private fields
    //primary constructor
    public CollectionUsageFindRequest(
      [NotNull] string filePath,
      int caretOffset
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
      CaretOffset = caretOffset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, out int caretOffset)
    {
      filePath = FilePath;
      caretOffset = CaretOffset;
    }
    //statics
    
    public static CtxReadDelegate<CollectionUsageFindRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var caretOffset = reader.ReadInt();
      var _result = new CollectionUsageFindRequest(filePath, caretOffset);
      return _result;
    };
    
    public static CtxWriteDelegate<CollectionUsageFindRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.CaretOffset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CollectionUsageFindRequest) obj);
    }
    public bool Equals(CollectionUsageFindRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && CaretOffset == other.CaretOffset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + CaretOffset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CollectionUsageFindRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("caretOffset = "); CaretOffset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: CollectionUsageFinderProtocol.kt:15</p>
  /// </summary>
  public sealed class CollectionUsageFindResponse : IPrintable, IEquatable<CollectionUsageFindResponse>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [NotNull] public string Message {get; private set;}
    
    //private fields
    //primary constructor
    public CollectionUsageFindResponse(
      bool success,
      [NotNull] string message
    )
    {
      if (message == null) throw new ArgumentNullException("message");
      
      Success = success;
      Message = message;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [NotNull] out string message)
    {
      success = Success;
      message = Message;
    }
    //statics
    
    public static CtxReadDelegate<CollectionUsageFindResponse> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var message = reader.ReadString();
      var _result = new CollectionUsageFindResponse(success, message);
      return _result;
    };
    
    public static CtxWriteDelegate<CollectionUsageFindResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      writer.Write(value.Message);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CollectionUsageFindResponse) obj);
    }
    public bool Equals(CollectionUsageFindResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Message == other.Message;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + Message.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CollectionUsageFindResponse (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("message = "); Message.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
